services:
  server:
    build:
      context: . # curernt directory
      dockerfile: Dockerfile
    container_name: chatapp-server
    image: chatapp-server:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
