name: Deploy chatApp BE to Hostinger VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy BE to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          CLIENT_ROOT_URL: ${{ secrets.CLIENT_ROOT_URL }}
          DB_CONNECT_URL: ${{ secrets.DB_CONNECT_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          envs: CLIENT_ROOT_URL,DB_CONNECT_URL,JWT_SECRET,JWT_REFRESH_SECRET,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET
          script: |
            set -e          # ← Stop immediately if any command fails

             # Fix git safe directory issue
             git config --global --add safe.directory /home/ubuntu/chatApp/chatApp-BE

             echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
             echo "🚀 Deploying Server..."
             echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

             # ── Pull latest code ──
             cd /home/ubuntu/chatApp/chatApp-BE
             git fetch origin main
             git reset --hard origin/main
             echo "✅ Code updated"

             # ── Go to umbrella folder ──
             cd /home/ubuntu/chatApp

             # ── Overwrite .env.server fresh every deploy ──
             cat > .env.server << EOF
             CLIENT_ROOT_URL=${CLIENT_ROOT_URL}
             DB_CONNECT_URL=${DB_CONNECT_URL}
             JWT_SECRET=${JWT_SECRET}
             JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
             CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
             CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
             CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
             EOF
             echo "✅ .env.server created"

             # ── Rebuild ONLY server ──
             sudo docker compose build server
             sudo docker compose up -d --no-deps server
             echo "✅ Server container restarted"

             sudo docker image prune -f
             echo "✅ Cleanup done"

             echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
             echo "🎉 Deployment successful!"
             echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
